#coding:utf-8
#-----------------------------------------------------------------
# pycparser: func_defs.py
#
# Using pycparser for printing out all the functions defined in a
# C file.
#
# This is a simple example of traversing the AST generated by
# pycparser. Call it from the root directory of pycparser.
#
# Eli Bendersky [https://eli.thegreenplace.net/]
# License: BSD
#-----------------------------------------------------------------
from __future__ import print_function
import sys

# This is not required if you've installed pycparser into
# your site-packages/ with setup.py
sys.path.extend(['.', '..'])

from pycparser import c_parser, c_ast, parse_file


# A simple visitor for FuncDef nodes that prints the names and
# locations of function definitions.
class FuncDefVisitor(c_ast.NodeVisitor):
    # 重写了 访问函数定义节点的函数 
    def visit_FuncDef(self, node):   # 函数名 visit_FuncDef  指定了 访问 函数定义的节点 
        print(type(node)             # FuncDef 函数定义 = FuncDecl函数声明 + Compound函数体
        print(type(node.decl)        # Decl类 父类
        print(type(node.decl.type))  # FuncDecl函数声明/PtrDecl指针声明/ArrayDecl数组声明/TypeDecl类型声明/
        if isinstance(node.decl.type,c_ast.FuncDecl):
            # 是函数定义
            print(type(node.decl.type.args))        # ParamList  参数列表
            print(type(node.decl.type.args.params)) # List 列表
            print(type(node.decl.type.args.params[0])) # Decl 定义
            print(type(node.decl.type.args.params[0].type)) #  PtrDecl/TypeDecl/ArrayDecl/FuncDecl ...
            print(type(node.decl.type.args.params[0].type.type)) #  TypeDecl/PtrDecl/ArrayDecl/FuncDecl ...
            print(type(node.decl.type.args.params[0].type.type.type))  # IdentifierType 标识符 int/float/../结构体
             
        print('%s at %s' % (node.decl.name, node.decl.coord))
              
    # 重写了 访问类型定义节点的函数 
    def visit_TypeDef(self, node): 
       print(type(node)             # TypeDef类型定义

def show_func_defs(filename):
    # Note that cpp is used. Provide a path to your own cpp or
    # make sure one exists in PATH.
    ast = parse_file(filename, use_cpp=True,
                     cpp_args=r'-Iutils/fake_libc_include')

    v = FuncDefVisitor()
    v.visit(ast)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename  = sys.argv[1]
    else:
        filename = 'examples/c_files/memmgr.c'

    show_func_defs(filename)
