#coding:utf-8
#-----------------------------------------------------------------
# pycparser: func_defs.py
#
# Using pycparser for printing out all the functions defined in a
# C file.
#
# This is a simple example of traversing the AST generated by
# pycparser. Call it from the root directory of pycparser.
#
# Eli Bendersky [https://eli.thegreenplace.net/]
# License: BSD
#-----------------------------------------------------------------
from __future__ import print_function
import sys

# This is not required if you've installed pycparser into
# your site-packages/ with setup.py
sys.path.extend(['.', '..'])

from pycparser import c_parser, c_ast, parse_file

class FuncCall_Visitor(c_ast.NodeVisitor):
    # 可以打印函数内部的函数调用
    def visit_FuncCall(self, node): 
        print(type(node))  

fcv = FuncCall_Visitor()

# A simple visitor for FuncDef nodes that prints the names and
# locations of function definitions.
class FuncDefVisitor(c_ast.NodeVisitor):
    # 函数定义
    def visit_FuncDef(self, node):    # 函数名 visit_FuncDef  指定了 访问 函数定义的节点 
        print(type(node))             # FuncDef 函数定义 = FuncDecl函数声明 + Compound函数体
        print(type(node.decl))        # Decl类 父类
        print(type(node.decl.type))   # FuncDecl函数声明/PtrDecl指针声明/ArrayDecl数组声明/TypeDecl类型声明/
        if isinstance(node.decl.type,c_ast.FuncDecl):
            # 是函数定义
            print(type(node.decl.type.args))        # ParamList  参数列表
            print(type(node.decl.type.args.params)) # List 列表
            print(type(node.decl.type.args.params[0])) # Decl 定义
            print(type(node.decl.type.args.params[0].type)) #  PtrDecl/TypeDecl/ArrayDecl/FuncDecl ...
            print(type(node.decl.type.args.params[0].type.type)) #  TypeDecl/PtrDecl/ArrayDecl/FuncDecl ...
            print(type(node.decl.type.args.params[0].type.type.type))  # IdentifierType 标识符 int/float/../结构体
             

        #print(type(node))                 # FuncDef 函数定义  pycparser.c_ast.FuncDef
        #print(node.param_decls)           # None
        #print(type(node.decl))            #  Decl  声明  
        #print(type(node.decl.name))       # 'str'  函数声明 的名字  函数名 
        
        # 函数返回值 特殊属性
        #print(type(node.decl.quals))      # 'list'
        #print(node.decl.storage[0])       # 'list' 函数返回值存储方式 (static)
        #print(type(node.decl.funcspec))   # 'list'
        
        #print(node.decl.init)             # 'NoneType'  
        #print(node.decl.bitsize)          # 'NoneType'
        
        #print(type(node.decl.type))       # 声明类型 FuncDecl/../  函数声明+函数体 = 函数定义
        #print(isinstance(node.decl.type,c_ast.FuncDecl))  # 判断类型 是函数声明
        #print(type(node.decl.type.args))                  # 函数参数列表 ParamList
        #print(type(node.decl.type.type))                  # 函数返回值 类型定义 TypeDecl
        
        # 函数参数 详情
        print("func: %s , param num: %d" % (node.decl.name, len(node.decl.type.args.params)))
        #print(type(node.decl.type.args.params))           # List
        #print(type(node.decl.type.args.params[0]))        # Decl 为定义类
        #print(type(node.decl.type.args.params[0].type))   # PtrDecl/../
        #print(type(node.decl.type.args.params[0].type.type)) #TypeDecl/../PtrDecl/..
        #print(type(node.decl.type.args.params[0].type.type.type)) #IdentifierType 标识符  int/float/char/结构体/联合/枚举 等
        #print(type(node.decl.type.args.params[0].type.type.type.names)) # 具体类型 标识符名称
        
        # 函数返回值详情
        print(type(node.decl.type.type))                    # 函数返回值 类型定义 TypeDecl
        print(     node.decl.type.type.declname)            # 函数类型的 名字  函数名
        print(type(node.decl.type.type.quals))              # 类型定义特殊属性  list
        print(type(node.decl.type.type.type))               # 标识符 IdentifierType 
        print(type(node.decl.type.type.type.names))         # 标识符 名字列表
        print(node.decl.type.type.type.names[0])            # unsigned
        print(node.decl.type.type.type.names[1])            # int
        
        #print(node.decl.type.coord)      # 代码位置
        print('%s %s at %s ' % (node.decl.name, '', node.decl.coord)) 
        
        # 打印函数内部的 函数调用
        fcv.visit(node)
        
    # 类型定义
    def visit_TypeDef(self, node): 
       print(type(node)             # TypeDef 类型定义
    # 函数声明       
    def visit_FuncDecl(self, node): 
       print(type(node)             # FuncDecl 函数声明

def show_func_defs(filename):
    # Note that cpp is used. Provide a path to your own cpp or
    # make sure one exists in PATH.
    ast = parse_file(filename, use_cpp=True,
                     cpp_args=r'-Iutils/fake_libc_include')

    v = FuncDefVisitor()
    v.visit(ast)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename  = sys.argv[1]
    else:
        filename = 'examples/c_files/memmgr.c'

    show_func_defs(filename)
